### ISSUE TITLE
アンドロイド端末上で解析エラーがでます。

### ISSUE THREAD

**Issue by tmdoi** [cerevo/hyourowgan_ble_sample#1]
開発チーム御中

大阪府立大学高専　土井です

はじめまして

HyouRowGan_BLE_Sample.apkをインストールしようとすると
アンドロイド端末上で解析エラーがでます。

供給されるアンドロイドのバージョンはいくつなのでしょうか？

**Comment by f-okuhara** [comment]
ソフトウェア担当の奥原です。

サンプルプログラムそのものはAndroid 4.4以降に対応、5.0以降推奨です。
AndroidでBLEのサポートが開始されたバージョンが4.3、最低限実用できるのが4.4、充分実用できるのが5.0以降という感じです。
4.3ではAPI実装が不十分なためサポートしていません。

apkについては、手元のAndroid 4.4.2と6.0の端末で動作することを確認しています。
ビルドのお手間をかけずに使っていただけることを期待して提供しているものですので、動作の保証まではいたしかねます。
お手元でソースコードからビルドしていただくのが一番確実です。

一点お願いになりますが、このコメントをお読みになりましたらチケットをクローズしていただけますでしょうか。
(サポート窓口を迂回するサポートは会社から禁止されていますが、自分が高専出身のため親近感もありモグリで対応しています。クローズを確認後、このコメントを削除させていただきます。)

内容につきましては、一担当者が私的に回答しているもので会社としての回答ではございませんのでよろしくお願いいたします。

**Comment by tmdoi** [comment]
ありがとうございました。
